#!/usr/bin/perl

#########################################################
# Chefy developed by Heitor Gouvêa                      #
# This work is licensed under MIT License               #
# Copyright (c) 2017 Heitor Gouvêa                      #
#                                                       #
# [+] AUTOR:        Heitor Gouvêa                       #
# [+] EMAIL:        hgouvea@protonmail.com              #
# [+] GITHUB:       https://github.com/GouveaHeitor     #
# [+] TWITTER:      https://twitter.com/GouveaHeitor    #
# [+] FACEBOOK:     https://fb.com/GouveaHeitor         #
#########################################################

use lib "./lib/";
use Chefy::Console;
use Chefy::Framework::Functions;

sub start {
	Chefy::Framework::Functions -> banner();
 	Chefy::Console -> new();
}

start();
