#!/usr/bin/perl

#########################################################
# Chefy developed by Heitor Gouvêa                      #
# This work is licensed under MIT License               #
# Copyright (c) 2017 Heitor Gouvêa                      #
#                                                       #
# [+] AUTOR:        Heitor Gouvêa                       #
# [+] EMAIL:        hi@heitorgouvea.me                  #
# [+] SITE:         http://heitorgouvea.me              #
# [+] GITHUB:       https://github.com/GouveaHeitor     #
# [+] TELEGRAM:     @GouveaHeitor                       #
#########################################################

use lib "./lib/";

sub main {
	my @services = @ARGV;

	if (@services) {
	}
}

main();
exit;
