requires "threads";
requires "Mojo::File";
requires "Find::Lib", "1.04";
requires "YAML::Tiny", "1.73";
requires "Masscan::Scanner";
requires "Net::DNS", "1.34";
requires "WWW::Mechanize", "2.11";
requires "Net::IP";
requires "UUID::Tiny", "1.04";
requires "WWW::Mechanize";
requires "WWW::Wappalyzer";
requires "Redis";