requires 'threads',             '2.26';
requires 'Mojo::File',          '9.41';
requires 'Find::Lib',           '1.04';
requires 'YAML::Tiny',          '1.76';
requires 'Masscan::Scanner',    '20200329.150259';
requires 'Net::DNS',            '1.51';
requires 'WWW::Mechanize',      '2.11';
requires 'Net::IP',             '1.26';
requires 'UUID::Tiny',          '1.04';
requires 'WWW::Mechanize',      '2.19';
requires 'WWW::Wappalyzer',     '2.00';
requires 'Redis',               '2.000';
requires 'IO::Socket::SSL',     '2.095';
requires 'DateTime::TimeZone',  '2.65';
requires 'List::MoreUtils';
requires 'JSON';
requires 'LWP::UserAgent';
requires 'XML::Simple';
requires 'Nmap::Scanner';
requires 'Image::ExifTool';
requires 'Mojolicious';
requires 'OpenAI::API';
requires 'Try::Tiny';
requires 'Readonly';
requires 'URI';
requires 'HTML::LinkExtor';
requires 'HTTP::Request::Common';
requires 'HTTP::Cookies';
requires 'Thread::Queue';
