#!/usr/bin/env perl

# Spellbook::Helper::Generate_UUID builds one or more UUID strings.

use strict;
use warnings;

use Test::More;
use Getopt::Long ();
use FindBin;
use lib "$FindBin::RealBin/../lib";

BEGIN {
    unless ( eval { require UUID::Tiny; 1 } ) {
        plan skip_all => 'UUID::Tiny is not installed';
    }
}

require Spellbook::Helper::Generate_UUID;

my $uuid_pattern = qr/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

# A single version 4 UUID.
my @one = Spellbook::Helper::Generate_UUID->new( [ '--version' => 4 ] );
is( scalar @one, 1, 'a single UUID is generated by default' );
like( $one[0], $uuid_pattern, 'the generated value is a well-formed UUID' );

# --repeat controls how many UUIDs are generated, and they should differ.
my @many = Spellbook::Helper::Generate_UUID->new( [ '--version' => 4, '--repeat' => 5 ] );
is( scalar @many, 5, '--repeat 5 generates five UUIDs' );
like( $_, $uuid_pattern, 'each generated value is a well-formed UUID' ) for @many;

my %seen = map { $_ => 1 } @many;
is( scalar keys %seen, 5, 'the generated version 4 UUIDs are unique' );

# The help branch returns usage text.
my $help = Spellbook::Helper::Generate_UUID->new( ['--help'] );
like( $help, qr/Generate_UUID/, 'help output names the module' );

# With no recognised arguments the module returns 0.
my $empty = Spellbook::Helper::Generate_UUID->new( [] );
is( $empty, 0, 'no arguments returns 0' );

done_testing();
